# This is a simple ansible playbook for install a minimal Fedora-System in a
# chroot-lioke manner on bare-metal. (In conjunction with a SuperMicro BMC).
#
# For refference you can finde the SuperMicro documentation under 
# --> https://bit.ly/3wjXXAb
---

- name: configure hardware-base RAID-1 for operating system
  block:
    - community.general.redfish_command:
        category: Systems
        command: SmcStorage.CreateVolume
        ControllerID: 0
        Raid: "RAID1"
        PhysicalDrives: '["HA-RAID.0.Disk.0", "HA-RAID.0.Disk.1"]'
        baseuri: {{ o_host_bmc }}
        username: {{ ansible-bmc-user }}
        password: {{ ansible-bmc-passowrd }}

    - community.general.redfish_command:
        category: Systems
        command: SmcHARAIDController.Save
        ControllerID: 0
        BIOSBootMode: 'PauseOnError'
        baseurl: {{ o_host_bmc}}

# original the plan was to mount an installation media as virtual media
# after some tests it seems more convinent to utilize a PXE-server

- name: attach os-installer and reboot machine
  block:
    - community.general.redfish_commmand:
        category: Manager
        command: VirtualMediaInsert
        basuri: '{{ o_host_bmc }}'
        username: {{ ansible-bmc-user }}
        password: {{ ansible-bmc-password }}
        virtual_media:
          image_url: {{ installer_iso }}
          media_types:
            - CD
            - DVD
      
    - community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        boot_override_mode: UEFI
        bootdevice: UsbCd
        basuri: {{ o_host_bmc }}
        username: {{ ansible-bmc-user }}
        passowrd: {{ ansible-bmc-password }}

    - community.general.redfish_command:
        category: Systems
        command: PowerForceRestart
        baseuri: {{ o_host_bmc }}
        username: {{ ansible-bmc-user }}
        password: {{ ansible-bmc-password }}


## installing fedora in an automated way
#  for this the new machine will boot in a minimal system with enabled sshd
#  the installation will be performed in a chroot env
- ansible.builtin.shell: |
    ip=$(arp -a | grep {{ o_primary_mac }} | cut -d ' ' -f | cut -c 2- | rev | cut -c 2- | rev)
    echo ip
  delegate_to: localhost
  register: installhost

- ansible.builtin.add_host:
    name: {{ installhost.stdout }}
    groups:
      - ai
    ansible_user: {{ install_sys_user }}
    ansible_password: {{ install_sys_password }}

- ansible.builtin.wait_for_connection:
  delegate_to: {{ installhost.stdout }}

# before we can deploy the operating system we require a proper
# configured filesystem.
#   - retrieve the size of the created raid
#   - create efi partition on this device with a size of 512 MB and
#     labled as EFI (later mounted as /boot)
#   - use the entire disk for operation system
- name: prepare host filesystem
  block:
    - ansible.builtin.command: 'lsblk -no SIZE /dev/sda | head -1'
      register: osdisk_size

    - community.general.parted:
        device: /dev/sda
        number: 1
        fs_type: fat32
        part_end: 512MB
        label: gpt
        flags: [ esp ]
        state: present

    - community.general.parted:
        device: /dev/sda
        number: 2
        fs_type: ext4
        part_start: 512MB
        state: present

    - anible.posix.mount:
        path: /mnt
        src: /dev/sda2
        fstype: ext4
        state: present

    - ansible.builtin.file:
        path: '/mnt/{{ item }}'
        state: directory
        loop:
          - 'boot'
          - 'proc'

    - ansible.posix.mount:
        path: /mnt/boot
        src: /dev/sda1
        fs_type: fat32
        state: present

    - ansible.posix.mount:
        path: /mnt/proc
        src: /proc
        fs_type: none
        opts: bind
        state: present


# finally install fedora from livesystem
- ansible.builtin.shell: |
    # installing base system
    dnf install --installroot=/mnt \
      --releasever=39 \
      --setopt=install_weak_deps=False \
      bash coreutils @Core

    # preconfigure system
    chroot /mnt

    # deploy management account
    chroot /mnt bash -c useradd {{ ansible_user }}

    # adding tailscale repo and deploy tailscale
    chroot /mnt bash -c dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    chroot /mnt bash -c dnf clean all
    chroot /mnt bash -c dnf install -y tailscale
    chroot /mnt bash -c systemctl enable tailscaled
    chroot /mnt bash -c tailscale up --authkey={{ tailscale_authkey }}
  delegate_to: {{ installhost.stdout }}